### ISSUE TITLE
Too many versions of tensorflow downloaded

### ISSUE THREAD

**Issue by Z-KN** [Arm-China/Compass_Integration#2]
When I try to install wheel (pip3 install dist/AIPUBuilder-*-cp38-cp38-linux_x86_64.whl), it will download too many versions of tensorflow (>10G). Can you select representative ones for getting to use portably?
![image](https://user-images.githubusercontent.com/50490656/210196895-9b41df64-b691-46bf-8293-a45f184c0105.png)

**Comment by ArmChinaOpensource** [comment]
fixed, thx @Z-KN
