### ISSUE TITLE
is there any plan to release aipucc/aipu_simulator/aipubuild codes?

### ISSUE THREAD

**Issue by zjd1988** [Arm-China/Compass_Integration#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ArmChinaOpensource** [comment]
I'm sorry it's not quite appropriate to discuss such issues here. You can consult here: https://aijishu.com/channel/xpu/questions
